version: "3.7"

services:
  jupyterlab:
    build:
      context: .
      cache_from:
        - $IMAGE_ID:latest
    user: root
    image: ml_bots_base
    container_name: ml_bots
    env_file:
      - .env
    volumes:
      # Relative path from the path where this YAML file exists (ml_bots/dockerfiles)
      - ../:/home/$NB_USER
    working_dir: /home/$NB_USER
