version: "3.7"

services:
  jupyterlab:
    build:
      context: .
      cache_from:
        - $IMAGE_ID:latest
    user: root
    container_name: ml_bots_base
    env_file:
      - .env
    volumes:
      - ~/ml_bots:/home/$NB_USER
    working_dir: /home/$NB_USER
