version: "3.7"
services:
  jupyterlab:
    build: .
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ~/ml_bots:/home/jovyan/work
    command: start.sh jupyter lab --NotebookApp.token=''