name: Docker

on:
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - v*
env:
  # image name
  IMAGE_NAME: ml_bots_base
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
jobs:
  # RUN UNIT TESTS
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build docker image
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          echo $IMAGE_ID >> ./dockerfiles/.env
          docker-compose --file ./dockerfiles/docker-compose.test.yml up -d
      - name: Test with pytest
        run: |
          docker exec $IMAGE_NAME pwd
          docker exec $IMAGE_NAME pytest ./work/src/tests
  # PUSH IMAGE
  push:
    # Trigger when unit tests are completed.
    needs: unittest
    runs-on: ubuntu-latest
    # pushイベント以外(PRなど)では実行されない
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION