name: Unittests and Push Docker Images

on:
  push:
    branches:
      - master
      - develop
      - feature/*
    tags:
      - v*
env:
  # image name
  IMAGE_NAME: ml_bots_base
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
jobs:
  # RUN UNIT TESTS
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build docker image
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          echo $IMAGE_ID >> ./dockerfiles/.env
          docker-compose --file ./dockerfiles/docker-compose.test.yml up -d
      - name: Test with pytest
        run: |
          docker exec $IMAGE_NAME ls
          docker exec $IMAGE_NAME pytest ./src/tests
  # PUSH IMAGE
  push:
    # Trigger when unit tests are completed.
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build container image for master branch.
        uses: docker/build-push-action@v2
        if: "contains( github.ref , 'master')"
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
      - name: Build container image for feature branch.
        uses: docker/build-push-action@v2
        if: "!contains( github.ref , 'master')"
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

